### ISSUE TITLE
Vertical Scrollbar + Fixed Header Row

### ISSUE THREAD

**Issue by chasseikindi** [hikalkan/jtable#1704]
How does one implement a vertical scrollbar with jTable?
Also, is it POSSIBLE to make the top header row persistent/sticky/fixed?

Thanks very much!

**Comment by chc88** [comment]
Not at the current time. More of us would be happy if a merge request would be made.

**Comment by javadbat** [comment]
i need it too can anyone help?

**Comment by tchoulihan** [comment]
Here's what worked for me:

```css
$('.jtable').wrap('<div class="jtable-main-container scroll-content" />');    
and

.scroll-content {
     overflow-y: auto;
    width:100%;
 }
div.jtable-main-container {
  height:100%;
}
```
