### ISSUE TITLE
How to do a fixed header when scrolling?

### ISSUE THREAD

**Issue by tchoulihan** [hikalkan/jtable#1896]
How is this done with jtable, I can't find anything?

**Comment by tchoulihan** [comment]
Found the solution:

Here's what worked for me:

```css
$('.jtable').wrap('<div class="jtable-main-container scroll-content" />');    
and

.scroll-content {
     overflow-y: auto;
    width:100%;
 }
div.jtable-main-container {
  height:100%;
}
```
